"""
============================================================
EMAIL SERVICE
Sends report card PDFs via email using SMTP.

Configuration via environment variables:
    SMTP_HOST       — SMTP server (default: smtp.gmail.com)
    SMTP_PORT       — SMTP port (default: 587)
    SMTP_USER       — Sender email
    SMTP_PASSWORD   — App password (not regular password)
    SMTP_FROM_NAME  — Sender display name (default: NeuroLearn)

For Gmail: Enable 2FA, create an App Password at
https://myaccount.google.com/apppasswords
============================================================
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import logging
logger = logging.getLogger("neurolearn.email")


SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_FROM_NAME = os.getenv("SMTP_FROM_NAME", "NeuroLearn")


def is_email_configured() -> bool:
    """Check if SMTP credentials are set."""
    return bool(SMTP_USER and SMTP_PASSWORD)


def send_plain_email(to_email: str, subject: str, body_text: str) -> dict:
    """
    Generic transactional email — used by password reset. Kept separate
    from send_report_email() (which is PDF-attachment-specific) rather
    than overloading that function's signature.

    Returns: { "success": bool, "message": str }
    """
    if not is_email_configured():
        logger.warning("SMTP not configured — email not sent")
        return {
            "success": False,
            "message": "Email not configured. Set SMTP_USER and SMTP_PASSWORD environment variables.",
        }
    try:
        msg = MIMEMultipart()
        msg["From"] = f"{SMTP_FROM_NAME} <{SMTP_USER}>"
        msg["To"] = to_email
        msg["Subject"] = subject
        msg.attach(MIMEText(body_text, "plain"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)

        return {"success": True, "message": f"Email sent to {to_email}"}
    except Exception as ex:
        logger.error(f"Failed to send email: {ex}")
        return {"success": False, "message": str(ex)}


def send_report_email(
    to_email: str,
    student_name: str,
    course_title: str,
    score: float,
    pdf_bytes: bytes,
    filename: str = "NeuroLearn_Report.pdf",
) -> dict:
    """
    Send report card PDF as email attachment.

    Returns:
        { "success": bool, "message": str }
    """
    if not is_email_configured():
        logger.warning("SMTP not configured — email not sent")
        return {
            "success": False,
            "message": "Email not configured. Set SMTP_USER and SMTP_PASSWORD environment variables.",
        }

    try:
        msg = MIMEMultipart()
        msg["From"] = f"{SMTP_FROM_NAME} <{SMTP_USER}>"
        msg["To"] = to_email
        msg["Subject"] = f"NeuroLearn Report Card — {course_title} ({score:.0f}%)"

        # HTML email body
        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #1a1a2e; max-width: 600px;">
            <div style="background: #2A5C1E; padding: 20px; border-radius: 8px 8px 0 0;">
                <h1 style="color: white; margin: 0; font-size: 22px;">NeuroLearn Report Card</h1>
            </div>
            <div style="background: #f7faf5; padding: 20px; border: 1px solid #d5ecd0;">
                <p>Hi <strong>{student_name}</strong>,</p>
                <p>Your assessment report for <strong>{course_title}</strong> is attached.</p>
                <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
                    <tr>
                        <td style="padding: 12px; background: white; border: 1px solid #d5ecd0; text-align: center;">
                            <div style="font-size: 28px; font-weight: bold; color: #4C9F38;">{score:.0f}%</div>
                            <div style="font-size: 11px; color: #6b6b80;">Assessment Score</div>
                        </td>
                    </tr>
                </table>
                <p>The attached PDF contains your full performance breakdown including
                behavioral-cue metrics, adaptive analysis, and personalized recommendations.</p>
                <p style="color: #6b6b80; font-size: 12px;">
                    This report was automatically generated by the NeuroLearn platform.
                </p>
            </div>
        </body>
        </html>
        """
        msg.attach(MIMEText(html, "html"))

        # Attach PDF
        pdf_attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
        pdf_attachment.add_header("Content-Disposition", "attachment", filename=filename)
        msg.attach(pdf_attachment)

        # Send
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)

        logger.info(f"Report emailed to {to_email}")
        return {"success": True, "message": f"Report sent to {to_email}"}

    except smtplib.SMTPAuthenticationError:
        logger.error("SMTP authentication failed")
        return {"success": False, "message": "SMTP authentication failed. Check credentials."}
    except Exception as e:
        logger.error(f"Email error: {e}")
        return {"success": False, "message": f"Failed to send email: {str(e)}"}
